// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import LoadingMessageController from "./loading_message_controller.js"
application.register("loading-message", LoadingMessageController)
