require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
      - vendor/bundle/**/*
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/controllers/feedback_forms_controller_spec.rb'
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/controllers/renewals_controller.rb'
    - 'app/controllers/requests_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.json.jbuilder'
    - 'config/environments/test.rb'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/checkout.rb'
    - 'app/models/patron.rb'
    - 'app/models/payment.rb'
    - 'app/models/request.rb'
    - 'app/services/symphony_client.rb'
    - 'config/application.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/mailers/feedback_mailer.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Style/WordArray:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'
