require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/controllers/feedback_forms_controller_spec.rb'
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
