require:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
      - bin/*
      - vendor/bundle/**/*
      - node_modules/**/*
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/controllers/feedback_forms_controller_spec.rb'
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/controllers/renewals_controller.rb'
    - 'app/controllers/requests_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.json.jbuilder'
    - 'config/environments/*.rb'
    - 'config/routes.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/symphony/checkout.rb'
    - 'app/models/symphony/patron.rb'
    - 'app/models/symphony/payment.rb'
    - 'app/models/symphony/request.rb'
    - 'app/services/symphony_client.rb'
    - 'app/models/folio/checkout.rb'
    - 'app/models/folio/patron.rb'
    - 'app/models/folio/payment.rb'
    - 'app/models/folio/request.rb'
    - 'app/services/folio_client.rb'
    - 'app/services/folio_graphql_client.rb'
    - 'config/application.rb'

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/summaries_helper.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/mailers/feedback_mailer.rb'
    - 'app/services/folio_graphql_client.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

Rails/ActionControllerFlashBeforeRender:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/features/**/*'

RSpec/VerifiedDoubleReference:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 15

Style/Documentation:
  Enabled: false

Style/WordArray:
  Exclude:
    - 'config/application.rb'
    - 'config/environments/test.rb'
    
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
  
FactoryBot/SyntaxMethods:
  Enabled: true
