require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/controllers/requests_controller.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.json.jbuilder'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'app/models/checkout.rb'
    - 'app/models/patron.rb'
    - 'app/services/symphony_client.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/controllers/feedback_forms_controller_spec.rb'
    - 'app/controllers/feedback_forms_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/contact_forms_controller.rb'
    - 'app/controllers/feedback_forms_controller.rb'
    - 'app/mailers/feedback_mailer.rb'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/controllers/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent
