dist: xenial
addons:
  chrome: stable

notifications:
  email: false

sudo: false
language: ruby
cache: bundler

rvm:
  - 2.6.3

env:
  global:
    - CC_TEST_REPORTER_ID=afca182781705a1379fa3cdc7d4fa2319c4fc7bb100e27969325255bdc54d0bc

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222 http://localhost &
