debug: false

folio:
  okapi_url: <%= ENV['OKAPI_URL'] %>
  online_service_point_id: 7c5abc9f-f3d7-4856-b8d7-6712462ca007
  graphql_url: <%= ENV['FOLIO_GRAPHQL_URL'] %>
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html:

internal_pages_flash_message_html: ''

internal_pages_flash_message_config: []

GLOBAL_ALERT: <%= true %>

borrow_direct_reshare:
  enabled: false

# Adding Illiad
sul_illiad: https://sul-illiad-test.stanford.edu/
illiad_api_key: 'AbC123'

analytics_debug: true

mailer_host: 'localhost'

cybersource:
  payment_url: https://secureacceptance.cybersource.com/pay
  access_key: 'change_me'
  secret_key: 'change_me'
  profile_id: 'change_me'
