GOOGLE_ANALYTICS_ID:
borrow_direct:
  api_key: ''
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html:

internal_pages_flash_message_html: ''

internal_pages_flash_message_config: []

GLOBAL_ALERT: <%= true %>

symphony:
  host:
  override: PASSWORD

BORROW_DIRECT_CODE: BORROW_DIRECT

scheduling: false

schedule_pickup:
  BUSINESS: false
  EAST-ASIA: false
  GREEN: false
  HOPKINS: false
  LAW: false

schedule_access:
  EAST-ASIA: false
  GREEN: false
  SPEC-COLL: false

libcal:
  BUSINESS:
    u: 69353
    lid: 4596
    id: 9430
    iid: 5088
    t: 'At the'
  LAW:
    u: 73555
    lid: 1122
    gid: 11656
    iid: 3313
    t: 'Pickup at Outside of Law Library'

cdl:
  url: http://requests.example.com

embed:
  url: https://embed.stanford.edu

purl:
  url: https://purl.stanford.edu
