GOOGLE_ANALYTICS_ID:
borrow_direct:
  api_key: ''
symws:
  url:
  headers: {}
  login_params: {}
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html: |-
  <h1 class="h3 alert-heading">Welcome to the new My Library Account!</h1>

  <p>My Account has been completely re-designed. It shows more information, highlights items that need attention, requires fewer steps, and is easier to use on mobile devices. <a href="https://library.stanford.edu/blogs/stanford-libraries-blog/2019/08/new-my-library-account">&raquo; Find out more</a></p>

  <p class="mb-0">Use the feedback link to let us know what you think!</p>

internal_pages_flash_message_html: |-
  <p>As of Monday, 9/9/19, we are having an issue with renewing materials due on 9/23/19.  Renewals will be available on Tuesday, 9/10/19.</p>

internal_pages_flash_message_config:
  - summaries
  - checkouts

symphony:
  host:
  override: PASSWORD

BORROW_DIRECT_CODE: BORROW_DIRECT
