debug: false

borrow_direct:
  api_key: ''

ils:
  client: SymphonyClient
  patron_model: Symphony::Patron

symws:
  url: https://example.com/symws
  headers: {}
  login_params: {}
  public_clientID:
folio:
  url: <%= ENV['OKAPI_URL'] %>
folio_graphql:
  url: <%= ENV['FOLIO_GRAPHQL_URL'] %>
sw:
  url: https://searchworks.stanford.edu/view/
EMAIL_TO: yolo@example.com
HOSTNAME: foo.example.com
ACCESS_SERVICES_EMAIL: greencirc@stanford.edu
RECAPTCHA:
  SITE_KEY: 6Lc6BAAAAAAAAChqRbQZcn_yyyyyyyyyyyyyyyyy
  SECRET_KEY: 6Lc6BAAAAAAAAKN3DRm6VA_xxxxxxxxxxxxxxxxx

home_page_flash_message_html:

internal_pages_flash_message_html: ''

internal_pages_flash_message_config: []

GLOBAL_ALERT: <%= true %>

symphony:
  host:
  override: PASSWORD

borrow_direct_reshare:
  enabled: false

# TODO: delete these after we move to FOLIO and get these codes directly from effectiveLocation
BORROW_DIRECT_CODE: BORROW_DIRECT
ILL_CODE: ILL

cdl:
  url: http://requests.example.com

embed:
  url: https://embed.stanford.edu

purl:
  url: https://purl.stanford.edu

analytics_debug: true

mailer_host: 'localhost'

cybersource:
  access_key: ~
  secret_key: ~
  payment_url: https://testsecureacceptance.cybersource.com/pay
  profile_id: wfgsulair