symws:
  url: https://example.com/symws
  headers:
      x-sirs-clientID: SymWSTestClient
  login_params:
    login: 'fake_user'
    password: 'some_password'
symphony:
  host: example.com

scheduling: true

schedule_pickup:
  BUSINESS: true
  EAST-ASIA: true
  GREEN: true
  HOPKINS: true

schedule_access:
  EAST-ASIA: true
  GREEN: true
  SPEC-COLL: true
