symws:
  url: https://example.com/symws
  headers:
      x-sirs-clientID: SymWSTestClient
  login_params:
    login: 'fake_user'
    password: 'some_password'
symphony:
  host: example.com

schedule_once:
  enabled: true
  green_pickup:
    enabled: true
  green_visits:
    enabled: true
  spec_visits:
    enabled: true
