symws:
  headers:
      x-sirs-clientID: SymWSTestClient
  login_params:
    login: 'fake_user'
    password: 'some_password'

symphony:
  host: example.com

folio:
  url: http://example.com

okapi:
  url: http://example.com
  login_params:
    username: user
    password: pass

debug: true
ils:
  client: FolioClient
  patron_model: Folio::Patron
