symws:
  headers:
      x-sirs-clientID: SymWSTestClient
  login_params:
    login: 'fake_user'
    password: 'some_password'
symphony:
  host: example.com

folio:
  url: 'https://user:password@okapi.stanford.edu'
folio_graphql:
  url: 'http://user:password@localhost:4000'
