name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: Configure bundler
      run: bundle config set --local without 'production'
    - name: Install dependencies
      run: bundle install
      run: yarn install
    - name: Run tests
      run: bundle exec rake
